### ISSUE TITLE
Error initializing cabal 

### ISSUE THREAD

**Issue by 2016rshah** [khanage/heineken#3]
When I tried to create a simple project (by doing `cabal run hein new Helloworld`) to test it out I ran into the following error:

```
Initialising cabal...
cabal: unrecognized option `--main-is=Main.hs'
hein: user error (Pattern match failure in do expression at src/Development/Heineken/New.hs:77:10-20)
```

I'm not entirely sure what I did wrong, but I would appreciate any suggestions or insight. Seems like an awesome project.

**Comment by khanage** [comment]
Which version of cabal are you using? I've got the latest on hackage and that seems to work ok on the big three platforms.

That error suggests that --main-is isn't defined in the version of cabal you're using!

**Comment by yurrriq** [comment]
I'm having the same issue on Mac OS X.

```
cabal --version
cabal-install version 1.18.0.5
using version 1.18.1.4 of the Cabal library
```

**Comment by yurrriq** [comment]
After running `cabal install cabal cabal-install` and fixing my symlinks:

```
cabal --version
cabal-install version 1.22.4.0
using version 1.22.3.0 of the Cabal library
```

Now `hein new ...` runs without issue. :+1:

**Comment by khanage** [comment]
Awesome, I think I should add something to the reader about versions of cabal required. Glad to hear it's working for you.

**Comment by 2016rshah** [comment]
I had to jump through a few hoops to try to update cabal but it works now and so does heineken. Thanks for the quick response and explanation. Cheers.

**Comment by yurrriq** [comment]
:beers:
