### ISSUE TITLE
README.md

### ISSUE THREAD

**Issue by 2016rshah** [khanage/heineken#4]
This is a feature request that I would be happy to help out on if you think it is a good idea. When you create a new project it should typically have some sort of README so perhaps while creating everything else we also create a README for the user in the git repo? Thoughts?

**Comment by khanage** [comment]
Sounds good. If you'd like to send a pull request you can, otherwise I'll try to take a look at it over the weekend. The code is still pretty bad (as I haven't decided on how to handle errors - maybe a continuation of some kind? EitherT?), but it is pretty trivial to add that into the New module.
